"""Writes frontend/allur_data.js (window.ALLUR_DATA) from data/allur_test_data/*.csv."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))

from app.testdata import load  # noqa: E402

if __name__ == "__main__":
    out = ROOT / "frontend" / "allur_data.js"
    out.write_text("// Generated by scripts/build_allur_data.py from data/allur_test_data. Do not edit by hand.\n"
                   f"window.ALLUR_DATA = {json.dumps(load(), ensure_ascii=False)};\n", encoding="utf-8")
    print("wrote", out)
